# https://shuxiao.wang/posts/zsh-refresh/

add_newline = true

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
# format = "[$symbol$branch]($style) "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[golang]
format = "[$symbol()]($style)"

[nodejs]
format = "via [ðŸ¤– $version](bold green) "

[cmd_duration]
format = "[$duration]($style) "
min_time = 3_000

[character]
# success_symbol = "[âœ”](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold blue) "

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user@]($style)"
disabled = false

[hostname]
ssh_only = true
format =  "[$hostname](bold yellow) "
disabled = false

[package]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

